resources:
- type: compute.v1.instance
  name: [DEPLOYMENT_NAME]-vm
  properties:
    zone: us-central1-f
    # Replace [PROJECT_ID] has to be replaced with your project id
    machineType: https://www.googleapis.com/compute/v1/projects/[PROJECT_ID]/zones/us-central1-f/machineTypes/f1-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-9
    # Replace [PROJECT_ID] has to be replaced with your project id
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/[PROJECT_ID]/global/networks/default
      # Access Config required to give the instance a public IP address
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
